# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_inscription_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnexionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pseudo', models.EmailField(max_length=254)),
                ('user_pass', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
